force-app/main/default/objects/ICS_AVM_ChatButtonToEPMAndLanguageMap__c/ICS_AVM_ChatButtonToEPMAndLanguageMap__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is to store chat buttons and its related EPM ID and language data</description>
    <label>ICS AVM ChatButton EPM and Lang Map</label>
</CustomObject>

force-app/main/default/objects/ICS_AVM_ChatButtonToEPMAndLanguageMap__c/fields/Chat_Button_Id__c.field-meta.xml
<CustomField>
    <fullName>Chat_Button_Id__c</fullName>
    <description>To store button id</description>
    <label>Chat Button Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ICS_AVM_ChatButtonToEPMAndLanguageMap__c/fields/Deployment_Id__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Id__c</fullName>
    <label>Deployment Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ICS_AVM_ChatButtonToEPMAndLanguageMap__c/fields/EPM_Id__c.field-meta.xml
<CustomField>
    <fullName>EPM_Id__c</fullName>
    <description>To store EPM Id</description>
    <label>EPM Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ICS_AVM_ChatButtonToEPMAndLanguageMap__c/fields/Is_Default__c.field-meta.xml
<CustomField>
    <fullName>Is_Default__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if it stores default button, deployment id</description>
    <label>Is Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ICS_AVM_ChatButtonToEPMAndLanguageMap__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>To store language</description>
    <label>Language</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ICS_AVM_ChatButtonsUtil.cls
/********************************************************************************************
* Name        : ICS_AVM_ChatButtonsUtil
* Test class  : ICS_AVM_ChatButtonsUtil_Test
* Author      : Priyabhavana - Popcornapps
* Date created: 31 - March - 2020
* Description : Return chat button id when provided epm id,language and deploymentId
*                
* Date              Created By                    User-Story   
* 31/03/2020        Popcornapps                   US951685
* ******************************************************************************************/
public with sharing class ICS_AVM_ChatButtonsUtil {
 
    Map<String, ChatandDeploymentIdWrapper> epmIdAndLanguageToChatandDepIdMap;
    String defaultButtonId;
    String defaultDeploymentId;
    // 06/04/2020 -US951685 (TA2259813)- Adding deploymentid as param 
    public ChatandDeploymentIdWrapper processEPMIdAndLanguage(String epmId,String language){
        ChatandDeploymentIdWrapper chatandDeploymentIdWrap = new ChatandDeploymentIdWrapper();
        Map<String, ICS_AVM_ChatButtonToEPMAndLanguageMap__c> chatButtonToEPMAndLangCustomMap = ICS_AVM_ChatButtonToEPMAndLanguageMap__c.getAll();
        
        if(chatButtonToEPMAndLangCustomMap != null && !chatButtonToEPMAndLangCustomMap.isEmpty()){
           epmIdAndLanguageToChatandDepIdMap = prepareEPMIdAndLangToChatButtonIdMap(chatButtonToEPMAndLangCustomMap); 
        }
        
        if(epmIdAndLanguageToChatandDepIdMap != null && !epmIdAndLanguageToChatandDepIdMap.isEmpty()){
           chatandDeploymentIdWrap = getChatButtonId(epmId,language);
        }
        return chatandDeploymentIdWrap;
    }
    
        
    /*───────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
    * @method   prepareEPMIdAndLangToChatButtonIdMap
    * @author   Priyabhavana
    * @param    chatButtonToEPMAndLangCustomMap - custom settings map
    * @return   epmIdAndLanguageToChatButtonIdMap 
    * ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
    */
    Map<String,ChatandDeploymentIdWrapper> prepareEPMIdAndLangToChatButtonIdMap(Map<String,ICS_AVM_ChatButtonToEPMAndLanguageMap__c> chatButtonToEPMAndLangCustomMap){
        epmIdAndLanguageToChatandDepIdMap = new Map<String,ChatandDeploymentIdWrapper>();
        for(String chatButtonName: chatButtonToEPMAndLangCustomMap.keySet()){
           ChatandDeploymentIdWrapper chatandDeploymentIdWrap = new ChatandDeploymentIdWrapper();
            if(chatButtonToEPMAndLangCustomMap.get(chatButtonName).Is_Default__c == true){
               defaultButtonId = chatButtonToEPMAndLangCustomMap.get(chatButtonName).Chat_Button_Id__c;
               defaultDeploymentId = chatButtonToEPMAndLangCustomMap.get(chatButtonName).Deployment_Id__c; 
            }
           chatandDeploymentIdWrap.chatButtonId = chatButtonToEPMAndLangCustomMap.get(chatButtonName).Chat_Button_Id__c;
           chatandDeploymentIdWrap.deploymentId = chatButtonToEPMAndLangCustomMap.get(chatButtonName).Deployment_Id__c;
           epmIdAndLanguageToChatandDepIdMap.put(chatButtonToEPMAndLangCustomMap.get(chatButtonName).EPM_Id__c+chatButtonToEPMAndLangCustomMap.get(chatButtonName).Language__c,chatandDeploymentIdWrap);
        }    
        return epmIdAndLanguageToChatandDepIdMap;
    }
    
    /*───────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
    * @method   getChatButtonId
    * @author   Priyabhavana
    * @param    epmIdAndLanguageToChatButtonIdMap,epmId,language,deploymentId
    * @return   buttonId 
    * ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
    */
    ChatandDeploymentIdWrapper getChatButtonId(String epmId,String language){
       ChatandDeploymentIdWrapper chatandDepIdWrap = new ChatandDeploymentIdWrapper();
        if(String.isNotBlank(epmId) && String.isNotBlank(language) && epmIdAndLanguageToChatandDepIdMap.containsKey(epmId+language)){
            chatandDepIdWrap.chatButtonId = epmIdAndLanguageToChatandDepIdMap.get(epmId+language).chatButtonId;
            chatandDepIdWrap.deploymentId = epmIdAndLanguageToChatandDepIdMap.get(epmId+language).deploymentId;
        }else{
            chatandDepIdWrap.chatButtonId = defaultButtonId;
            chatandDepIdWrap.deploymentId = defaultDeploymentId;
        }
        return chatandDepIdWrap;
    }

    public class ChatandDeploymentIdWrapper{
        public String chatButtonId;
        public String deploymentId;
    }
    
}